### ISSUE TITLE
use an interface instead of *testing.T

### ISSUE THREAD

**Issue by errordeveloper** [dlespiau/kube-test-harness#21]
It's unfortunate that [`*testing.T`](https://godoc.org/testing#T) not an interface.

I want to use this library with Ginkgo and [documentation](https://onsi.github.io/ginkgo/#third-party-integrations) suggests that I should create an interface. Any other ideas are welcome! 👍

**Comment by errordeveloper** [comment]
@dlespiau could you please assign this to me?

**Comment by dlespiau** [comment]
Done and invited you as a collaborator!
